Amazing Mountain Website
zaidansari42/Amazing-Mountain-Responsive pull request #1
Opened 2022-06-11 21:27 UTC by zaidansari42

2022-06-13 20:20 UTC, mujeeb100 requested changes
not a responsive

2022-06-14 05:28 UTC, zaidansari42 commented
> not a responsive

Please try to View it in a Desktop/Laptop. In mobile desktop version it's not showing, but in Laptop it is responsive as designed

2022-06-26 08:01 UTC, nehalskdev approved these changes

2022-06-26 08:01 UTC, nehalskdev commented on styles.css
> +  display: none;
What is the use of it?

2022-06-26 08:01 UTC, nehalskdev commented on styles.css
> +  justify-content: center;
```suggestion
  display: grid;
  Place-items: center;
```

2022-06-28 13:37 UTC, zaidansari42 commented on styles.css
> +  display: none;
To make the default view of the checkbox hidden. And then use label as a button for this input.

2022-06-28 13:38 UTC, merged